### ISSUE TITLE
[graphql-tag/loader] Allow importing named fragments in .graphql

### ISSUE THREAD

**Issue by LevanArabuli** [apollographql/graphql-tag#251] opened 2019-04-22 10:13 UTC
Currently importing fragments in .graphql files imports everything, would be nice to have named imports. The problem is that Apollo Client will send all fragments with request, instead of filtering only what's actually used, eventually it results in server error `Fragment "X" is never used`.

```
// fragments.graphql
fragment info1 on Entity1 {
	id
	name
}

fragment info2 on Entity2 {
	title
	description
}
```

```
// someQuery.graphql

#import { info2 } from './fragments.graphql'
.
.
.
```

As a workaround we can split fragments into very granular files for sure, but it would be nice to have this feature.

**Comment by dobesv** [comment] 2019-05-02 21:53
Dupe of https://github.com/apollographql/graphql-tag/issues/102 ?

**Closed** 2019-05-03 03:57 UTC

**Comment by toddpadwick** [comment] 2021-06-10 07:32
Can anyone tell me how I get this to work? I can't find specific documentation on it. 

I have queries in GQL files in which I have fragments which are also used in other gql query files.

`getEntry.gql`

I need to import a specific fragment from my `fragments.gql` file but I get a syntax error due to the import statement along with unknown fragment.

how do I use es6 js import statement inside the gql files?

**Comment by dobesv** [comment] 2021-06-10 16:59
> how do I use es6 js import statement inside the gql files?

You can't use es6 import in gql files.  Some GraphQL setups do allow another kind of import, though.

e.g. https://www.graphql-tools.com/docs/schema-loading/

**Comment by dobesv** [comment] 2021-06-10 17:01
I guess the fix in #102 was not actually a fix for this issue, because this issue is talking about imports written into the `.graphql` files where as #102 is talking about importing graphql files from a JavaScript file.

**Comment by clieee** [comment] 2021-06-29 12:51
So importing specific fragments from a .gql file that contains multiple fragments will simply not work as it is right now? And will result in error message?:
```Error: Fragment "[NAME OF FRAGMENT]" is never used.```
